#!/usr/bin/env bash

# bootstrap-env.sh
# Generates dynamic port configuration based on the worktree/environment name to prevent conflicts.

ENV_NAME=${1:-$(basename "$PWD")}
PROJECT_NAME=${2:-"agenticflow"}

# Strip the project prefix to avoid double-naming in docker-compose.yaml
ENV_NAME=${ENV_NAME#"$PROJECT_NAME-"}

ENV_FILE=".env"

if [ "$ENV_NAME" = "main" ] || [ "$ENV_NAME" = "master" ] || [ "$ENV_NAME" = "$PROJECT_NAME" ]; then
    PROXY_PORT=18080
    POSTGRES_PORT=5432
    CHROMA_PORT=8000
else
    # Simple hash based on ENV_NAME to get deterministic ports per environment
    OFFSET=$(echo "$ENV_NAME" | cksum | awk '{print $1 % 1000}')
    
    # Avoid 0 offset just in case to clearly distinguish from main
    if [ "$OFFSET" -eq 0 ]; then
        OFFSET=1
    fi
    
    PROXY_PORT=$((18080 + OFFSET))
    POSTGRES_PORT=$((5432 + OFFSET))
    CHROMA_PORT=$((8000 + OFFSET))
fi

echo "Setting up environment configuration for '$ENV_NAME'..."

cat <<EOF > "$ENV_FILE"
# Auto-generated by bootstrap-env.sh
PROJECT_NAME=$PROJECT_NAME
ENV_NAME=$ENV_NAME
PROXY_PORT=$PROXY_PORT
POSTGRES_PORT=$POSTGRES_PORT
CHROMA_PORT=$CHROMA_PORT
EOF

echo "Generated $ENV_FILE with:"
echo "  PROXY_PORT=$PROXY_PORT"
echo "  POSTGRES_PORT=$POSTGRES_PORT"
echo "  CHROMA_PORT=$CHROMA_PORT"
echo ""
echo "Note: Make sure to export these or include them in your run commands, e.g.:"
echo "  set -a; source $ENV_FILE; set +a"
